name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Run tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Create and push semver tag
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          noNewCommitBehavior: warn
          noVersionBumpBehavior: warn
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          name: ${{ steps.semver.outputs.next }}
          token: ${{ secrets.ACCESS_TOKEN }}