name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
      - name: Run tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Get semver tag
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noNewCommitBehavior: warn
          noVersionBumpBehavior: warn
      - name: Create Release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: ${{ steps.semver.outputs.next }}
          prerelease: true